User.create(:username => "michael", :email => "michael@angel.com", :password => "michael")
User.create(:username => "raphael", :email => "raphael@angel.com", :password => "raphael")
User.create(:username => "gabriel", :email => "michael@angel.com", :password => "gabriel")
User.create(:username => "alpha", :email => "alpha@mail.com", :password => "alpha")

Mission.create(:content => "Love", :user_id => "1")
Mission.create(:content => "Peace", :user_id => "1")
Mission.create(:content => "Joy", :user_id => "1")
Mission.create(:content => "Prosperity", :user_id => "2")
Mission.create(:content => "Life", :user_id => "2")
